syntax = "proto3";

// protoc --go_out=. --go-grpc_out=. dfs.proto

package dfs;

option go_package = ".";

// could change the data types of the request and response messages
service masterTracker {
  rpc requestUpload(UploadRequest) returns (UploadResponse);
  rpc requestDownload(DownloadRequest) returns (DownloadResponse);
  rpc heartbeat(HeartbeatRequest) returns (Ack);
  rpc notifyFileStored(NotifyFileStoredRequest) returns (Ack);
  rpc ListFiles(EmptyRequest) returns (FileDetailsResponse);
}

service dataKeeper {
  rpc replicateFile(ReplicateFileRequest) returns (Ack);
  rpc requestUpload(DataKeeperUploadRequest) returns (UploadResponse);
  rpc requestDownload(DownloadRequest) returns (DataKeeperDownloadResponse);
}

message EmptyRequest {}

message DataKeeperUploadRequest {
  bool replication = 1;
}

message FileDetails {
  int64 id = 1;
  string name = 2;
  string hash = 3;
  int64 size = 4;
  string createdAt = 5;
}

message FileDetailsResponse { repeated FileDetails fileDetails = 1; }

message UploadRequest { string fileName = 1; }

message UploadResponse {
  string ip = 1;
  string port = 2;
}

message DownloadRequest { string fileName = 1; }

message DownloadResponse {
  repeated string ids = 1;
  repeated string ips = 2;
  repeated string ports = 3;
}

message DataKeeperDownloadResponse {
  string ip = 1;
  string port = 2;
}

message HeartbeatRequest {
  string id = 1;
  string ip = 2;
  string port = 3;
}

message NotifyFileStoredRequest {
  string datakeeperId = 1;
  string filePath = 2;
  string fileName = 3;
  string fileHash = 4;
  int64 fileSize = 5;
  bool replication = 6; // false upload, true replicate
}

message ReplicateFileRequest {
  int64 fileId = 1;
  repeated string ids = 2;
  repeated string ips = 3;
  repeated string ports = 4;
  string fileName = 5;
  string filePath = 6;
}

message Ack {
  bool success = 1;
  string message = 2;
  ErrorCode errorCode = 3;
}

enum ErrorCode {
  FILE_ALREADY_EXISTS = 0;
  FILE_NOT_FOUND = 1;
  FETAL_ERROR = 2;
}