syntax = "proto3";

package dfs;

option go_package = ".";

// could change the data types of the request and response messages
service masterTracker {
    rpc requestUpload (UploadRequest) returns (UploadResponse);
    rpc requestDownload (DownloadRequest) returns (DownloadResponse);
    rpc heartbeat (HeartbeatRequest) returns (Ack);
    rpc notifyFileStored (NotifyFileStoredRequest) returns (Ack);
}

service dataKeeper {
    rpc replicateFile (ReplicateFileRequest) returns (Ack);
}

message UploadRequest {
    string fileName = 1;
}

message UploadResponse {
    string ip = 1;
    int32 port = 2;
}

message DownloadRequest {
    string fileName = 1;
}

message DownloadResponse {
    repeated string ips = 1;
    repeated int32 ports = 2;
}

message HeartbeatRequest {
    string id = 1;
    string ip = 2; 
    int32 port = 3;
}

message NotifyFileStoredRequest {
    string dataKeeperIp = 1;
    string dataKeeperPort = 2;
    string filePath = 3;
    string fileName = 4;
    bool replication = 5; // false upload, true replicate
}

message ReplicateFileRequest {
    string fileName = 1;
    string filePath = 2;
    string destinationIp = 3;
    int32 destinationPort = 4;
}

    

message Ack {
    bool success = 1;
    string message = 2;
}