syntax = "proto3";


// protoc --go_out=. --go-grpc_out=. dfs.proto

package dfs;

option go_package = ".";

// could change the data types of the request and response messages
service masterTracker {
    rpc requestUpload (UploadRequest) returns (UploadResponse);
    rpc requestDownload (DownloadRequest) returns (DownloadResponse);
    rpc heartbeat (HeartbeatRequest) returns (Ack);
    rpc notifyFileStored (NotifyFileStoredRequest) returns (Ack);
}

service dataKeeper {
    rpc requestUpload (datakeeperRequest) returns (UploadResponse);
    rpc replicateFile (ReplicateFileRequest) returns (Ack);
    rpc requestDownload (DownloadRequest) returns (DataKeeperDownloadResponse);
}

message datakeeperRequest {
}

message UploadRequest {
    string fileName = 1;
}

message UploadResponse {
    string ip = 1;
    string port = 2;
}

message DownloadRequest {
    string fileName = 1;
}

message DownloadResponse {
    repeated string ips = 1;
    repeated string ports = 2;
}

message DataKeeperDownloadResponse {
    string ip = 1;
    string port = 2;
}

message HeartbeatRequest {
    string id = 1;
    string ip = 2;
    string port = 3;
}

message NotifyFileStoredRequest {
    string datakeeperId = 1;
    string filePath = 2;
    string fileName = 3;
    bool replication = 4; // false upload, true replicate
}

message ReplicateFileRequest {
    string fileName = 1;
    string filePath = 2;
    string destinationIp = 3;
    string destinationPort = 4;
}

message Ack {
    bool success = 1;
    string message = 2;
}